export enum LandType {
  Clear = 'Clear',
  Rough = 'Rough',
  Road = 'Road',
  Water = 'Water',
  Rock = 'Rock',
  Wall = 'Wall',
  Tiberium = 'Tiberium',
  Beach = 'Beach',
  Ice = 'Ice',
  Tunnel = 'Tunnel',
  Railroad = 'Railroad',
  Weeds = 'Weeds',
  Cliff = 'Cliff',
}